name: coffee_time
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.5.0
  material_design_icons_flutter: 3.4.4595
  uuid: ^2.0.2
  page_indicator: ^0.3.0
  expandable: ^3.0.1
  url_launcher: ^5.2.5
  intl: ^0.16.0
  logger: ^0.7.0+2
  equatable: ^0.6.1
  google_maps_flutter: ^0.5.21+11
  http: ^0.12.0+4
  freezed_annotation: ^0.7.1
  shared_preferences: ^0.5.6+1
  flutter_bloc: ^3.2.0
  geolocator: ^5.2.1
  cached_network_image: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  bloc_test: ^3.1.0
  effective_dart: ^1.2.0
  build_runner: ^1.7.4
  freezed: ^0.9.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/mock/cafe.json
    - assets/mock/cafe_detail.json
    - assets/table.jpg
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  fonts:
    - family: HandDrawnIcons
      fonts:
        - asset: assets/fonts/HandDrawnIcons.ttf
    - family: Amatic
      fonts:
        - asset: assets/fonts/AmaticSC-Regular.ttf
        - asset: assets/fonts/Amatic-Bold.ttf
          weight: 700
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
